### ISSUE TITLE
Licensing: Please add a license to this repository

### ISSUE THREAD

**Issue by Tarasus** [CipherBitCorp/VolumeButtonHandler#1]
Hello! 
I would like to use this repository as a dependence in my project. As [github suggests](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#choosing-the-right-license), an unlicensed repository is protected by the default copyright laws, so I can't use it, just view. 

Please add a license to this repository, or I'll be forced to look for alternatives for your code.

**Comment by kaanselhep** [comment]
Hi there,

No problem. License has been added.
Hope it helps.

**Comment by Tarasus** [comment]
Woah, that was FAST. Thank you!
